### ISSUE TITLE
Examples not working[Bug] 

### ISSUE THREAD

**Issue by nfernandezsanz** [kiki7000/discord.py-components#100]
Hi!
I am trying the examples and the buttons are created but I am always getting "This interaction failed", I am using the last version of the library and Python 3.10.

**Comment by Damego** [comment]
What's version of discord.py?

**Comment by nfernandezsanz** [comment]
Discord.py 2.0.0

**Comment by Damego** [comment]
discord.py v2 and discord_components are incompatible

**Comment by nfernandezsanz** [comment]
Which version of discord py are you using? 1.7.3?

**Comment by Damego** [comment]
Yes

**Comment by nfernandezsanz** [comment]
Nice! I changed that and Its working! Thank you very much for this quick support!
