### ISSUE TITLE
[Bug] Getting an error when trying to use buttons on the default example

### ISSUE THREAD

**Issue by ManDaMan002** [kiki7000/discord.py-components#16]
I was trying to use the example for the buttons, but i'm getting the same error over and over again

```
"Command raised an exception: TypeError: send() got an unexpected keyword argument 'components'"
```

i'm doing the **exact** same thing as in the example, am i using something incorrectly?

**Comment by kiki7000** [comment]
![image](https://user-images.githubusercontent.com/51841836/119772249-d7b48c00-bef9-11eb-9dd9-c4fc9d1056ca.png)
Did you did this?

**Comment by ManDaMan002** [comment]
Ok, that fixed that error, but now i'm getting a new one

```
Command raised an exception: AttributeError: 'NoneType' object has no attribute 'request'
```

**Comment by kiki7000** [comment]
Could you put DiscordComponents(bot) inside on_ready?
