### ISSUE TITLE
[Bug] wait_for_interaction check doesn’t work.

### ISSUE THREAD

**Issue by AiroPi** [kiki7000/discord.py-components#17]
## Bug Line
> Where is the bug? (line URL)

## Excpected Action
> What did you expect the module to do?

## Actual Action
> What actually happened?

## Reproducing the action
> How could you reproduce the action?

## Possible Solution
> How do you think you can fix this bug?

## Environment
> What is the version of the python?

## Check
- [ ] Are you using the newest version?
- [ ] Does this bug occurs security issues?

**Comment by kiki7000** [comment]
Update the module and try it again plz!
