### ISSUE TITLE
Make Docs.

### ISSUE THREAD

**Issue by injoon5** [kiki7000/discord.py-components#2]
@kiki7000 현재 https://github.com/injoon5/discord.py-buttons 에서 Docs를 만드는 중입니다. 일단 1차로 완성하면 여기에 올릴테니 그 뒤로 수정해야 할 것들을 알려주시면 감사하겠습니다. 

그런데 영어로 다 만들면 대부분의 사용자층인 한국인들이 혼란을 겪을것 같아 어느 언어로 해야 할까요?

- [ ] 1차 완성
- [ ] 피드백 받기
- [ ] 피드백 반영
- [ ] 메인 리포에 적용

**Comment by kiki7000** [comment]
그냥 DOCS는 SPHINX 사용하려고 합니다
제가 조금 만들어놓았는데 푸시하면 알려드릴게요!

일단 기본으로 영어로 하게하고 한국어 번역본도 만들예정입니다!

**Comment by kiki7000** [comment]
이슈 닫겠습니다!
