### ISSUE TITLE
[Bug] on_interact remove self in cogs

### ISSUE THREAD

**Issue by Baptiste-Taho** [kiki7000/discord.py-components#33]
## Bug Line
https://github.com/kiki7000/discord.py-components/blob/f542bbd2de21a4174c7c35665ad43d42caa88d07/discord_components/client.py#L438-L442

## Excpected Action
Disptach the function with the decorator `client.on_interact("button_click")` and pass the context argument

## Actual Action
Disptach the function with the decorator `client.on_interact("button_click")` and pass only one argument.
For a better explanation : here is my code
```
@dbb.on_interact("button_click")
async def button_click(self, ctx):
    ...
```
I'm in a cog so I really need `self`, but with the current solution that you propose, the context is put in the self variable, and the ctx is empty. So that I no longer have a self.

## Reproducing the action
You have to use the `on_interact` decorator in a cog

## Possible Solution
I created an alternative creating a new discord.py event which works very well, and which offers the possibility of having, in addition to `self`, the discord.py context by default and that of the module. I did not dare to do a PR because there is already the `on_interact`, but I find that my solution works better. Don't hesitate to telle me if you want it.

## Environment
Python 3.8.3 with all requirements needed (in a venv)

## Check
- [x] Are you using the newest version?
- [ ] Does this bug occurs security issues?

Other little question, there is a Discord?

**Comment by kiki7000** [comment]
Thank you for the issue!
I am fixing this

And https://discord.gg/pKM6stqPxS this is the discord server

**Comment by kiki7000** [comment]
```py
@commands.Cog.listener()
async def on_button_click(res):
 ...
Upgrade the module to 0.5.0 and use this
```

**Comment by Baptiste-Taho** [comment]
Thank you very much, have a nice day!

And thank you for this lib
