### ISSUE TITLE
`await ddb.wait_for_interact("button_click")` always times out

### ISSUE THREAD

**Issue by Neehier** [kiki7000/discord.py-components#35]
## Bug Line
`res = await ddb.wait_for_interact("button_click")`

## Excpected Action
Wait until a button is pressed.

## Actual Action
Doesn't notice the button being pressed, everything after the _Bug Line_ does not get executed. Discord shows _This interaction failed_.

## Environment
Python 3.8.10

## Check
- [x] Are you using the newest version?
- [ ] Does this bug occurs security issues?

**Comment by kiki7000** [comment]
Fixed on 0.4.9

**Comment by BlackThunder01001** [comment]
If you have `change_discord_methods = False` that could be the issue. Try without it.

**Comment by Shaqalito** [comment]
The bug is still occurring on version 0.5.1.1
