### ISSUE TITLE
[Bug] Setting the label to None or "" displays None if you edit the components. 

### ISSUE THREAD

**Issue by Kanin** [kiki7000/discord.py-components#46]
## Bug Line
https://github.com/kiki7000/discord.py-components/blob/master/discord_components/button.py#L172-L177

## Excpected Action
If the label is None it shouldn't display at all (given there's an emoji)

## Actual Action
If you edit a message to add additional components the label displays as None.

## Reproducing the action
Create a message with a button with the label set to None, then add another button to that message. You will notice that at first the label doesn't display at all but then when you add another, it displays as None.

## Possible Solution
N/A

## Environment
Python 3.9.5

## Check
- [X] Are you using the newest version?
- [ ] Does this bug occurs security issues?

**Comment by kiki7000** [comment]
Checked
Going to be fixed on the next update :)

**Comment by kiki7000** [comment]
Fixed on 0.5.2.4
