### ISSUE TITLE
[Bug] When fetching the buttons of a message, it doesn't return their rows.

### ISSUE THREAD

**Issue by Kanin** [kiki7000/discord.py-components#47]
## Bug Line
https://github.com/kiki7000/discord.py-components/blob/master/discord_components/client.py

## Excpected Action
Return the list of buttons with the rows ([[Button1, Button2, Button3, Button4, Button5], [Button6]])

## Actual Action
It returns a single list of buttons ([Button1, Button2, Button3, Button4, Button5, Button6])

## Reproducing the action
Fetch a message with more than one row of buttons

## Possible Solution
Provide the rows

## Environment
Python 3.9.5

## Check
- [X] Are you using the newest version?
- [ ] Does this bug occurs security issues?

**Comment by kiki7000** [comment]
Checked

**Comment by Kanin** [comment]
> Checked

Elaborate on checked, is this a bug or is this a me thing 👀

**Comment by kiki7000** [comment]
bug

**Comment by kiki7000** [comment]
Fixed on 0.5.2.4
