### ISSUE TITLE
[Bug] Button slways shows "This interaction failed" even if there is no error raised and the interaction worked.

### ISSUE THREAD

**Issue by Shaqalito** [kiki7000/discord.py-components#55]
## Excpected Action
> Respond to the interaction without an error

## Actual Action
> Shows under the button "This interaction failed" every time even when no error is raised
![Capture of the error on discord](https://user-images.githubusercontent.com/79249599/120079331-9d8eea00-c0b3-11eb-8a6f-1818d052a745.PNG)

## Reproducing the action
```
await ctx.send(embed= em, components=[
    Button(label= "Clear Kicked List", style=4, id="clear_kicked_button"),
  ])

      while True:
        res = await client.wait_for("button_click")
        if res.component.id == "clear_kicked_button":
          print("clicked kicked")
          with open("kicked_users.json", "r") as f:
            kicked_users = json.load(f)

            if kicked_users == "{}":
              em = Embed(title="Aucun utilisateur n'a été kick", color= 0xFF5BF8)
              await ctx.send(embed= em)
            else:
              kicked_users.clear()

              confem = Embed(title= "La liste de Kick a été clear", color= 0xFF5BF8)
              await ctx.send(embed= em)
          
          with open("kicked_users.json", "w") as f:
            json.dump(kicked_users, f, indent=4)
```

## Environment
> Python 3.8.2

## Check
- [x] Are you using the newest version?
- [ ] Does this bug occurs security issues?

**Comment by kiki7000** [comment]
I think you didn't responded 
edit `await ctx.send(embed = em` to `await res.respond(ephemeral = False, embed = em)`

**Comment by Shaqalito** [comment]
Thank youuuu it solved my problem
