### ISSUE TITLE
[Bug] async send_component_message method does not have delete_after attribute.

### ISSUE THREAD

**Issue by BenTang1939** [kiki7000/discord.py-components#59]
## Bug
The module's `send_component_message()` method does not have the `delete_after(float)` attribute, which makes it problematic to make previous code that utilizes `delete_after()` compatible with the module.

## Possible workarounds
I've worked around this by creating a separate method that deletes a message after using `asyncio.sleep()`.
This issue can also be avoided if DiscordComponents(bot, `change_discord_methods`) is set to False.

## Environment
Running python 3.8.5, discord API 1.7.0, discord_components 0.5.2.4

**Comment by kiki7000** [comment]
Checked 👍🏻

**Comment by kiki7000** [comment]
fixed
