### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by helish88** [kiki7000/discord.py-components#7]
![изображение](https://user-images.githubusercontent.com/52331802/119716169-81017080-be6d-11eb-8c2d-c6773e84f82f.png)

**Comment by FeelsBadMan1** [comment]
Hi, try the same thing but use a underscore instead of "-"

**Comment by Jorgen1040** [comment]
You shouldn't be using `discord-buttons`. The new name of the library is `discord-components`. (See 97359359411feaf4eaa61f9e9e62e32aa942b9a2) You can find it on [PyPi](https://pypi.org/project/discord-components/). 

`discord-buttons` is outdated now.

**Comment by helish88** [comment]
![изображение](https://user-images.githubusercontent.com/52331802/119727531-122b1400-be7b-11eb-8079-1c9130f32ca3.png)

**Comment by Jorgen1040** [comment]
@helish88 I don't know what you are asking about since you just sent an image, however I can see that you need to swap "button" with "component" in `content=f'{res.button.label} clicked'`. But you'll probably still get an error from the issues I fixed in PR #10. 

If you don't want to wait for that to be merged you could download directly from my fork via:

```
pip install git+https://github.com/Jorgen1040/discord.py-components.git@1a83a617e17bf2e36534130e89277fc054ad6149#egg=discord-components
```

Just make sure to uninstall the old version first

**Comment by kiki7000** [comment]
It should work now

**Comment by helish88** [comment]
yep, it works, thx

**Comment by FeelsBadMan1** [comment]
I now reinstalled discord-components and uninstall discord_buttons. now i not have the json error anymore but i now have this one:
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "D:\Downloads\Python\python 3.8.7\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:/my_python_projects/MongoDB Test/mongosetup.py", line 42, in on_message
    await msg.channel.send(
  File "D:\Downloads\Python\python 3.8.7\lib\site-packages\discord_components\client.py", line 67, in send_component_msg_prop
    return await self.send_component_msg(ctxorchannel, *args, **kwargs)
  File "D:\Downloads\Python\python 3.8.7\lib\site-packages\discord_components\client.py", line 187, in send_component_msg
    data = await self.bot.http.request(
  File "D:\Downloads\Python\python 3.8.7\lib\site-packages\discord\http.py", line 192, in request
    async with self.__session.request(method, url, **kwargs) as r:
AttributeError: 'NoneType' object has no attribute 'request'
```

**Comment by kiki7000** [comment]
Was the bot ready?
