### ISSUE TITLE
Docs website is empty

### ISSUE THREAD

**Issue by GingerGigiCat** [kiki7000/discord.py-components#70]
The [readthedocs website for discord-components ](https://discord-components.readthedocs.io/en/latest/) is empty.

It is supposed to show the docs for discord-components. In bing, it still shows what the site used to show, as in the below screenshot
![image](https://user-images.githubusercontent.com/75206318/120224952-47997e00-c23c-11eb-931d-5ac07e56abbb.png)

When going to the website, clicking on "Edit on github" tries to go to https://github.com/kiki7000/discord.py-components/blob/master/index.rst but gives a 404 error.

Edit:
I looked in the commit history and found that it was commit f0767071e0d1d409245c76cbbdd4b8f681a94a40 that removed the docs folder. 
![image](https://user-images.githubusercontent.com/75206318/120226268-ca233d00-c23e-11eb-969a-dbbfba875717.png)

**Comment by kiki7000** [comment]
You can use [this](https://discord-components.readthedocs.io/en/0.5.2.4/) for now
