### ISSUE TITLE
[Bug] Bot mentions regardless of its AllowedMentions

### ISSUE THREAD

**Issue by seojin200403** [kiki7000/discord.py-components#73]
## Excpected Action
I've set its allowed_mentions to discord.AllowedMentions.none() and expects it not to mention anyone.

## Actual Action
It mentions as if no filter is applied.

## Reproducing the action
set its allowed_mentions to discord.AllowedMentions.none()
declare DiscordComponents with change_discord_methods = True
reply to a message

## Possible Solution
It is happening when change_discord_methods is enabled. It is surely to cause of this issue.

## Environment
3.9
library: most recent

## Check
- [x] Are you using the newest version?
- [ ] Is this bug related to security issues?

**Comment by kiki7000** [comment]
Could you show me an example?

**Comment by kiki7000** [comment]
![image](https://user-images.githubusercontent.com/51841836/120439373-6a06d500-c3bd-11eb-9914-a9049d2b4396.png)
![image](https://user-images.githubusercontent.com/51841836/120439386-6d9a5c00-c3bd-11eb-9727-c7d99fb9b791.png)
Fixed

**Comment by seojin200403** [comment]
It is not working properly when allowed_mentions is not explictly set.
Needs to follow client's allowed mentions.

**Comment by seojin200403** [comment]
Reproduce:
set allowed_mentions to discord.AllowedMentions.none() and reply to a message
