### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by OGContent** [kiki7000/discord.py-components#77]
## Bug Line
> Where is the bug? (line URL)
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message

## Excpected Action
> What did you expect the module to do?
for it to send 3 buttons
## Actual Action
> What actually happened?
gave an error
## Reproducing the action
> How could you reproduce the action?
            await ctx.channel.send(
                components=[
                    Button(style=ButtonStyle.blue, label="Blue"),
                    Button(style=ButtonStyle.red, label="Red"),
                    Button(style=ButtonStyle.URL, label="url", url="https://example.org"),
                ],
              )
## Possible Solution
> How do you think you can fix this bug?

## Environment
> What is the version of the python?
3.8
## Check
- [ ] Are you using the newest version?
- [ ] Is this bug related to security issues?

**Comment by PythonSerious** [comment]
This error is correct, provide a content field when sending the message
you cannot send a message without content or an embed.

**Comment by OGContent** [comment]
> This error is correct, provide a content field when sending the message
> you cannot send a message without content or an embed.

Oh, ok its fixed now ty
