### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by helish88** [kiki7000/discord.py-components#78]
somehow discord.py-components block few random commands of my main bot and block entire on_command_error. I tested all commands with buttons on test bot and they work perfectly
someone else is faced with such a problem who has "big" bots?
my bot is on 1200 guilds 
I use [AutoShardedBot](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html?highlight=#discord.ext.commands.AutoShardedBot)

after I removed discord.py-components everything works as usual
## Check
- [X ] Are you using the newest version?
- [ ] Is this bug related to security issues?

**Comment by FightMan01** [comment]
Well, yes I also reported something else in #72 .
