### ISSUE TITLE
[Bug] Discord Buttons & Components

### ISSUE THREAD

**Issue by FeelsBadMan1** [kiki7000/discord.py-components#8]
Hey. today discord released the buttons but somehow i find 2 codeexamples in the docs one use buttons and one use components. if i use the components exaple i get a json not seziable error and if i use buttons i get this:
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "D:\Downloads\Python\python 3.8.7\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:/my_python_projects/MongoDB Test/mongosetup.py", line 31, in on_message
    m = await msg.channel.send(
  File "D:\Downloads\Python\python 3.8.7\lib\site-packages\discord_buttons\client.py", line 57, in send_button_msg_prop
    return await self.send_button_msg(ctxorchannel, *args, **kwargs)
  File "D:\Downloads\Python\python 3.8.7\lib\site-packages\discord_buttons\client.py", line 150, in send_button_msg
    data = await self.bot.http.request(
  File "D:\Downloads\Python\python 3.8.7\lib\site-packages\discord\http.py", line 192, in request
    async with self.__session.request(method, url, **kwargs) as r:
AttributeError: 'NoneType' object has no attribute 'request'
```
anyone knows a solution?

**Comment by helish88** [comment]
same error 
```bash
AttributeError: 'NoneType' object has no attribute 'from_json'```

**Comment by Jorgen1040** [comment]
I have a fix. Just gimmie a moment and I'll set up a PR

**Comment by Jorgen1040** [comment]
Nvm. I guess i was a little to quick to read this issue, my PR fixes the error that @helish88 gets. 
But I think your error stems from using `discord-buttons` and not the updated `discord-components` @FeelsBadMan1

**Comment by FeelsBadMan1** [comment]
> Nvm. I guess i was a little to quick to read this issue, my PR fixes the error that @helish88 gets.
> But I think your error stems from using `discord-buttons` and not the updated `discord-components` @FeelsBadMan1

Okey it is good that you solved to error from the other one that had almost the same. I defently tried both modules buttons aswell as components. while using the components i get this errorlog:
```
 json not seziable
 ```
