### ISSUE TITLE
[Add a Feature] Change documentation layout

### ISSUE THREAD

**Issue by Ari24-cb24** [kiki7000/discord.py-components#9]
## What feature
> It would be nice to change the layout of the documentation because things like (https://discord-components.readthedocs.io/en/latest/pages/client.html#discord_components.client.DiscordComponents.send_component_msg) are really unclear. You can't really see what type of parameter the method takes in.

## Advantages
> More readabillity

## Check
- [ ] Is this feature related to this module?
- [x] Can this feature be implemented?
- [ ] Does this new feature requires the user to change the code?

**Comment by Ari24-cb24** [comment]
forget everything I said Im dumb
Still, the text above could need some readabillity improvment

**Comment by kiki7000** [comment]
Checked!
