### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by TheShubhendra** [kiki7000/discord.py-components#95]
Can you please add [hacktoberfest](https://hacktoberfest.digitalocean.com) topic in this repository so that contributors can participate in that by contributing in the repository and pr for this repository can be considered for the participation.

**Comment by kiki7000** [comment]
Do I just have to register?

**Comment by TheShubhendra** [comment]
> Do I just have to register?

Yes, do register there and add hacktoberfest topic on repo.
```
A repository/project is considered to be participating in Hacktoberfest if the 'hacktoberfest' topic is present and is accepting public contributions via pull requests.
An individual pull request can also be opted-in directly by adding the 'hacktoberfest-accepted' label.
```
[READ MORE HERE](https://hacktoberfest.digitalocean.com/resources/participation)

**Comment by kiki7000** [comment]
Added the tag
